---
- name: Installing and removing Nginx 
  hosts: web
  tasks:
    - name: Installing Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Removing Nginx
      apt:
        name: nginx
        state: absent
