---
- name: Show request response
  hosts: web
  tasks:
    - name: Installing curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: curl httpbin.org API
      shell:
        cmd: 'curl -X GET "https://httpbin.org/get" -H  "accept: application/json"'
      register: curl_output
    
    - name: curl request response
      debug: var=curl_output.stdout_lines

    - name: Removing curl
      apt:
        name: curl
        state: absent
